using System;
using System.IO;
using TerraLoom.Core.Editor;
using TerraLoom.Core.Unity;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;

namespace TerraLoom.Integration.Editor
{
    /// <summary>Own isolated assets/configuration. All landscape geometry is generated by
    /// the runtime component, never hand-repaired in the saved scene.</summary>
    public static class WaterfallLandscapeBuilder
    {
        public const string Root="Assets/TerraLoom/Integration/Generated/WaterfallPrototype";
        public const string Scene=IntegrationSampleBuilder.Root+"/TerraLoomWaterfallPrototype.unity";
        [MenuItem("Tools/TerraLoom/Integration/Build Waterfall Landscape Prototype")]
        public static void Interactive(){if(EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())BuildBatch();}
        public static void BuildBatch()
        {
            Directory.CreateDirectory(Root);AssetDatabase.Refresh();
            var scene=EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);
            var host=new GameObject("TerraLoom waterfall: bounded runtime landscape experiment");host.AddComponent<TerraLoomWorld>();
            var recipe=host.AddComponent<WaterfallLandscapePrototype>();recipe.Seed=4102026;
            recipe.TerrainMaterial=Save(new Material(Shader.Find("Universal Render Pipeline/Terrain/Lit")){name="Original prototype terrain"},"Terrain.mat");
            var types=new[]{LandscapeSurfaceRecipe.Surface.Meadow,LandscapeSurfaceRecipe.Surface.DampSediment,LandscapeSurfaceRecipe.Surface.WeatheredRock,LandscapeSurfaceRecipe.Surface.DryGravel};
            recipe.GroundLayers=new TerrainLayer[4];
            for(int i=0;i<4;i++)
            {
                var color=Save(LandscapeSurfaceRecipe.Create(types[i],false),types[i]+"Color.asset");
                var normal=Save(LandscapeSurfaceRecipe.Create(types[i],true),types[i]+"Normal.asset");
                var layer=new TerrainLayer{diffuseTexture=color,normalMapTexture=normal,tileSize=Vector2.one*2,normalScale=.6f,smoothness=i==1?.25f:.07f};
                // Slightly fresher meadow, retaining the original grain/normal recipe.
                if(i==0){var pixels=color.GetPixels();for(int p=0;p<pixels.Length;p++)pixels[p]*=new Color(1.03f,1.13f,.83f,1);color.SetPixels(pixels);color.Apply();EditorUtility.SetDirty(color);}
                recipe.GroundLayers[i]=Save(layer,types[i]+".terrainlayer");
            }
            recipe.RockMaterial=Lit("Rock",Color.white,recipe.GroundLayers[2].diffuseTexture,recipe.GroundLayers[2].normalMapTexture);
            recipe.BarkMaterial=Lit("Bark",new Color(.24f,.20f,.14f),recipe.GroundLayers[2].diffuseTexture,null);
            recipe.GrassMaterial=Lit("Grass",new Color(.28f,.36f,.10f),null,null);recipe.GrassMaterial.SetFloat("_Cull",0);
            var leaf=new Texture2D(128,128,TextureFormat.RGBA32,true){name="Original individual serrated leaf",wrapMode=TextureWrapMode.Clamp};
            var leafPixels=new Color[128*128];for(int y=0;y<128;y++)for(int x=0;x<128;x++)
            {
                float u=(x+.5f)/128,v=(y+.5f)/128,mid=Mathf.Sin(v*Mathf.PI)*(.29f+.015f*Mathf.Sin(v*120));
                float alpha=Mathf.Abs(u-.5f)<mid?1:0;
                float vein=Mathf.Exp(-Mathf.Abs(u-.5f)*100)*.12f;
                leafPixels[y*128+x]=new Color(.27f+v*.12f+vein,.43f+v*.13f+vein,.075f+v*.045f,alpha);
            }
            leaf.SetPixels(leafPixels);leaf.Apply();leaf=Save(leaf,"Leaf.asset");
            recipe.LeafMaterial=Lit("Leaf",Color.white,leaf,null);recipe.LeafMaterial.SetFloat("_AlphaClip",1);recipe.LeafMaterial.SetFloat("_Cutoff",.5f);recipe.LeafMaterial.EnableKeyword("_ALPHATEST_ON");recipe.LeafMaterial.SetFloat("_Cull",0);recipe.LeafMaterial.renderQueue=2450;
            recipe.LeafMaterial.enableInstancing=true;recipe.RockMaterial.enableInstancing=true;recipe.BarkMaterial.enableInstancing=true;
            recipe.WaterMaterial=Save(new Material(Shader.Find("TerraLoom/Prototype/WaterfallLandscapeWater")){name="Original river pool water"},"Water.mat");
            recipe.FallMaterial=Save(new Material(recipe.WaterMaterial){name="Original descending waterfall water"},"Fall.mat");
            recipe.FallMaterial.SetFloat("_Fall",1);recipe.FallMaterial.SetColor("_BaseColor",new Color(.19f,.38f,.34f));recipe.FallMaterial.SetColor("_WaveColor",new Color(.44f,.61f,.55f));
            var sun=new GameObject("Sun").AddComponent<Light>();sun.type=LightType.Directional;sun.intensity=1.5f;sun.shadows=LightShadows.Soft;sun.transform.rotation=Quaternion.Euler(43,-35,0);
            RenderSettings.ambientMode=AmbientMode.Flat;RenderSettings.ambientLight=new Color(.56f,.62f,.67f);
            RenderSettings.fog=true;RenderSettings.fogMode=FogMode.Linear;RenderSettings.fogColor=new Color(.63f,.73f,.77f);RenderSettings.fogStartDistance=105;RenderSettings.fogEndDistance=250;
            var sky=Save(new Material(Shader.Find("Skybox/Procedural")){name="Prototype atmospheric sky"},"Sky.mat");sky.SetColor("_GroundColor",new Color(.36f,.41f,.34f));sky.SetFloat("_AtmosphereThickness",.8f);RenderSettings.skybox=sky;RenderSettings.sun=sun;
            var camera=new GameObject("Main Camera").AddComponent<Camera>();camera.tag="MainCamera";camera.clearFlags=CameraClearFlags.Skybox;camera.fieldOfView=65;camera.nearClipPlane=.08f;camera.farClipPlane=350;
            AssetDatabase.SaveAssets();EditorSceneManager.SaveScene(scene,Scene);
            Debug.Log("Waterfall prototype configuration saved; enter Play to build original terrain, water, rocks and vegetation. This is NOT general Rivers waterfall integration.");
        }
        private static Material Lit(string name,Color color,Texture texture,Texture normal)
        {
            var m=new Material(Shader.Find("Universal Render Pipeline/Lit")){name="Original prototype "+name};m.SetColor("_BaseColor",color);m.SetFloat("_Smoothness",.12f);
            if(texture)m.SetTexture("_BaseMap",texture);if(normal){m.SetTexture("_BumpMap",normal);m.EnableKeyword("_NORMALMAP");m.SetFloat("_BumpScale",.6f);}
            return Save(m,name+".mat");
        }
        private static T Save<T>(T asset,string name)where T:UnityEngine.Object
        {
            string path=Root+"/"+name;var old=AssetDatabase.LoadAssetAtPath<T>(path);
            if(old){EditorUtility.CopySerialized(asset,old);UnityEngine.Object.DestroyImmediate(asset);EditorUtility.SetDirty(old);return old;}
            AssetDatabase.CreateAsset(asset,path);return asset;
        }
    }
}
